<a href="https://colab.research.google.com/github/FujiminoDeliaMary/ArtfullCode/blob/main/FouilleDonnee/3-ANN/TP3_ANN_Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importation des Librairies

In [8]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import csv

from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.autograd as autograd
import torch.optim as optim

## 1. Préparation des données

1.1 Importer les données Train et Test

In [13]:
from google.colab import drive
drive.mount('/content/drive')

train = pd.read_csv('/content/drive/My Drive/Data_Titanic/train_clean.csv')
test = pd.read_csv('/content/drive/My Drive/Data_Titanic/test_clean.csv')

train.head()


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


PassengerId  Survived  Pclass  Sex  Age  Fare  Embarked  IsAlone  Title
0            1         0       3    1    1     0         0        0      1
1            2         1       1    0    2     3         1        0      3
2            3         1       3    0    1     1         0        1      2
3            4         1       1    0    2     3         0        0      3
4            5         0       3    1    2     1         0        1      1

In [12]:
test.head()

PassengerId  Pclass  Sex  Age  Fare  Embarked  IsAlone  Title
0          892       3    1    2     0         2        1      1
1          893       3    0    2     0         0        0      3
2          894       2    1    3     1         2        1      1
3          895       3    1    1     1         0        1      1
4          896       3    0    1     1         0        0      3

1.2 Depuis le Dataframe train, charger les features d'apprentissage dans un array numpy X_alltrain, et les labels (données à prévoir) dans un array numpy y_alltrain

In [14]:
X_alltrain = train.drop(columns=["Survived"]).to_numpy()
y_alltrain = train["Survived"].to_numpy()

1.3 Séparer les features et les labels en deux parties (train et dev), en attribuant 10% des exemples aux données de dev. afficher les nombres de lignes et de colonnes pour les 4 arrays.

In [26]:
X_train, X_dev, Y_train, Y_dev = train_test_split(X_alltrain, y_alltrain, test_size=0.1, random_state=1)

print("X_train :\n", X_train.shape)
print("X_dev :\n", X_dev.shape)
print("Y_train :\n", Y_train.shape)
print("Y_dev :\n", Y_dev.shape)

X_train :
 (801, 8)
X_dev :
 (90, 8)
Y_train :
 (801,)
Y_dev :
 (90,)


1.4 Afficher les 10 premières lignes de features et les 10 premiers labels.

In [30]:
print(X_train[:10])

[[663   1   1   2   2   0   1   1]
 [585   3   1   1   1   1   1   1]
 [704   3   1   1   0   2   1   1]
 [ 48   3   0   1   0   2   1   2]
 [869   3   1   2   1   0   1   1]
 [453   1   1   1   2   1   1   1]
 [ 95   3   1   3   0   0   1   1]
 [ 20   3   0   2   0   1   1   3]
 [878   3   1   1   0   0   1   1]
 [879   3   1   1   0   0   1   1]]


In [29]:
print(Y_train[:10])

[0 0 0 1 0 0 0 1 0 0]


## 2. Définition du réseau de neurone

2.1 Définir et instancier une classe Titanic Model avec les caractéristiques suivantes :
- deux  couches cachées de 50 neurones.
- deux classes en sortie : Survivant ou non
- Des fonctions d'activation RELU
- un dropout paramétrable pour les 2 couches cachées

In [ ]:
class TitanicModel(nn.Module):


2.2 : Définir des paramètres de nombre d'epochs (50) et de learning_rate (0.01)

2.3 définir la taille du minibatch à 50. En déduire le nombre de boucle pour chaque epoch.

2.4 Définir un fonction de coût de type CrossEntropy

2.5. Définir un optimizer de type Adam, sans oublier le learning rate

## 3. Apprentissage

3.1 exécuter l'apprentissage du modèle.
- Créer une boucle sur les epochs, qui contient elel-même une boucle sur les minibatchs.
- A chaque nouvelle itération sur les epochs, mélanger les données avec la méthode shuffle.
- Tous les 5 epochs afficher la valeur de la fonction de cout

3.2 Calculer la précision de la prévision sur les données dev

3.3 Calculer prévisions sur les données de tests

3.4 Générer le fichier résultat et l'envoyer sur kaggle
Quel est votre score et votre classement ?

3.5 (Optionnel) Exécuter une Cross Validationd ans une boucle pour trouver les meilleures valeurs de learning rate, de keep_prob et de nombre d'epochs.

Cross_Validation avec skkearn : https://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators